# This file was generated by the {rix} R package v0.17.2 on 2026-01-18
# with following call:
# >rix(date = latest_date,
#  > r_pkgs = c("BiocManager",
#  > "dplyr",
#  > "ggplot2",
#  > "DESeq2",
#  > "pasilla",
#  > "knitr",
#  > "testthat",
#  > "apeglm",
#  > "KernSmooth",
#  > "tibble",
#  > "quarto",
#  > "pheatmap",
#  > "RColorBrewer",
#  > "gridExtra",
#  > "tidyr"),
#  > system_pkgs = c("pandoc"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-14.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      apeglm
      BiocManager
      DESeq2
      dplyr
      ggplot2
      gridExtra
      KernSmooth
      knitr
      pasilla
      pheatmap
      quarto
      RColorBrewer
      testthat
      tibble
      tidyr;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      pandoc
      R
      quarto
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
